const selector=document.getElementById('camera-selector'),active=document.getElementById('active-camera');
const messages=new Map(),presetCache=new Map(),diagnosticsCache=new Map();let cameras=[],selectedId=localStorage.getItem('multicam-active-camera')||'',feedTimer=null,logTimer=null,renderedLogs='',activeTab='console';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const cap=(n,e)=>`<span class="cap${e?'':' off'}">${esc(n)}</span>`;const currentCamera=()=>cameras.find(c=>c.id===selectedId);
function renderSelector(){if(!cameras.length){selector.innerHTML='<option>No configured cameras</option>';selector.disabled=true;active.className='empty';active.textContent='No configured cameras were returned by the proxy.';return}selector.innerHTML=cameras.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');if(!cameras.some(c=>c.id===selectedId))selectedId=cameras[0].id;selector.value=selectedId;selector.disabled=false}
function presetLabel(p){const pt=p.position?.pan_tilt||{},z=p.position?.zoom||{};const coords=[pt.x!=null?`x=${pt.x}`:'',pt.y!=null?`y=${pt.y}`:'',z.x!=null?`z=${z.x}`:''].filter(Boolean).join(', ');return `${p.name||'(unnamed)'} [${p.token}]${coords?` — ${coords}`:''}`}
function presetOptions(camera){const list=presetCache.get(camera.id)||[];if(!list.length)return '<option value="">Load presets first</option>';return '<option value="">Select a saved position</option>'+list.map(p=>`<option value="${esc(p.token)}" data-name="${esc(p.name||'')}">${esc(presetLabel(p))}</option>`).join('')}
function syncPresetName(){const s=document.getElementById('preset-selector'),n=document.getElementById('preset-name');if(!s||!n)return;const o=s.options[s.selectedIndex];n.value=s.value?(o?.dataset.name||''):'';n.disabled=!s.value;const b=active.querySelector('[data-command="save-preset"]');if(b)b.disabled=!s.value}
function updateMessage(id){if(id!==selectedId)return;const e=active.querySelector('.message'),m=messages.get(id);if(!e)return;e.className=`message ${m?.ok?'ok':m?'bad':''}`;e.textContent=m?m.text:''}
function diagnosticsMarkup(id){const d=diagnosticsCache.get(id);return d?esc(JSON.stringify(d,null,2)):'Run read-only diagnostics to query the selected camera.'}
function renderActive(){const c=currentCamera();if(!c)return;const state=c.connection_state||(c.available===false?'unavailable':'available'),caps=c.capabilities||{},disabled=c.available===false||!caps.pan_tilt,m=messages.get(c.id),diag=diagnosticsCache.get(c.id);active.className='';active.innerHTML=`<section class="card">
<div class="card-head">
  <div class="camera-identity"><div class="camera-title-row"><h2 class="camera-name">${esc(c.name)}</h2><span class="status ${state==='unavailable'?'bad':state==='untested'?'untested':''}">${esc(state)}</span></div><div class="meta">${esc(c.driver)} · ${esc(c.host)} · ${esc(c.listen||'')}</div></div>
  <div class="feed-header-control"><div><h3>Live feed</h3><div class="hint">Opt-in snapshot feed</div></div><label class="toggle"><input id="feed-toggle" type="checkbox" ${c.feed_enabled?'checked':''} ${c.feed_supported?'':'disabled'}> Enabled</label></div>
</div>
<div class="workspace">
  <div class="feed-panel">${c.feed_enabled?`<div class="feed-box"><img id="feed-image" alt="${esc(c.name)} live snapshot"></div>`:`<div class="feed-placeholder">Enable the live feed to observe PTZ, zoom, and preset operations.</div>`}</div>
  <div class="control-panel">
    <div class="control-section"><h3>Pan / tilt</h3><div class="controls"><button class="ptz up" data-command="move" data-tilt="1" ${disabled?'disabled':''}>↑</button><button class="ptz left" data-command="move" data-pan="-1" ${disabled?'disabled':''}>←</button><button class="ptz stop" data-command="stop" ${disabled?'disabled':''}>■</button><button class="ptz right" data-command="move" data-pan="1" ${disabled?'disabled':''}>→</button><button class="ptz down" data-command="move" data-tilt="-1" ${disabled?'disabled':''}>↓</button></div></div>
    <div class="control-section"><h3>Zoom</h3><div class="zoom"><button data-command="zoom" data-direction="out" ${caps.zoom?'':'disabled'}>Zoom out</button><button data-command="zoom" data-direction="in" ${caps.zoom?'':'disabled'}>Zoom in</button></div></div>
    <div class="control-section"><div class="section-head"><h3>Presets</h3><button data-command="load-presets" ${caps.presets?'':'disabled'}>Load presets</button></div><div class="preset-row"><select id="preset-selector">${presetOptions(c)}</select><div class="preset-actions"><button data-command="goto-preset" ${caps.presets?'':'disabled'}>Go to</button><button data-command="refresh-presets" ${caps.presets?'':'disabled'}>Refresh</button></div></div><div class="preset-edit"><input id="preset-name" maxlength="40" placeholder="Preset name" disabled><button data-command="save-preset" disabled>Save current position</button></div><div class="caps">${cap('Pan / tilt',!!caps.pan_tilt)}${cap('Zoom',!!caps.zoom)}${cap('Presets',!!caps.presets)}${cap('Live feed',!!c.feed_supported)}</div></div>
  </div>
</div>
<div class="evidence-panel"><div class="tabs"><button class="tab ${activeTab==='console'?'active':''}" data-tab="console">Console log</button><button class="tab ${activeTab==='diagnostics'?'active':''}" data-tab="diagnostics">Camera diagnostics</button></div>
  <div id="console-panel" class="tab-panel ${activeTab==='console'?'active':''}"><div class="panel-toolbar"><span></span><button id="clear-console" type="button">Clear view</button></div><pre id="console" class="console">Loading logs…</pre></div>
  <div id="diagnostics-panel" class="tab-panel ${activeTab==='diagnostics'?'active':''}"><div class="panel-toolbar"><span id="diagnostics-time" class="diagnostics-time">${diag?`Collected ${esc(diag.collected_at||'')}`:'Not collected yet'}</span><button id="run-diagnostics" type="button">Run read-only diagnostics</button></div><pre id="diagnostics" class="console">${diagnosticsMarkup(c.id)}</pre></div>
</div>
<div class="footer-row"><div class="message ${m?.ok?'ok':m?'bad':''}">${m?esc(m.text):''}</div></div>${c.error?`<div class="error">${esc(c.error)}</div>`:''}
</section>`;syncFeedTimer(c);syncLogTimer();syncPresetName()}
function syncFeedTimer(c){if(feedTimer)clearInterval(feedTimer);feedTimer=null;if(!c.feed_enabled)return;const refresh=()=>{const i=document.getElementById('feed-image');if(i)i.src=`/api/cameras/${encodeURIComponent(c.id)}/snapshot.jpg?_=${Date.now()}`};refresh();feedTimer=setInterval(refresh,1500)}
async function loadLogs(){const box=document.getElementById('console');if(!box)return;try{const r=await fetch(`/api/cameras/${encodeURIComponent(selectedId)}/logs`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);const text=(d.entries||[]).map(e=>`${e.timestamp} [${e.level}] ${e.message}`).join('\n');if(text===renderedLogs)return;const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<24;box.textContent=text;renderedLogs=text;if(nearBottom)box.scrollTop=box.scrollHeight}catch(e){box.textContent='Unable to load logs: '+e.message}}
function syncLogTimer(){if(logTimer)clearInterval(logTimer);renderedLogs='';loadLogs();logTimer=setInterval(loadLogs,1000)}
async function runDiagnostics(){const button=document.getElementById('run-diagnostics'),box=document.getElementById('diagnostics'),time=document.getElementById('diagnostics-time');if(!button||!box)return;button.disabled=true;box.textContent='Collecting camera-reported ONVIF attributes…';try{const d=await post('diagnostics');diagnosticsCache.set(selectedId,d.result);box.textContent=JSON.stringify(d.result,null,2);if(time)time.textContent=`Collected ${d.result.collected_at||''}`;messages.set(selectedId,{ok:true,text:'Diagnostics completed'});updateMessage(selectedId)}catch(e){box.textContent='Diagnostics failed: '+e.message;messages.set(selectedId,{ok:false,text:e.message});updateMessage(selectedId)}finally{button.disabled=false}}
async function loadCameras(render=true){const r=await fetch('/api/cameras',{cache:'no-store'});if(!r.ok)throw new Error(`Status request failed: HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d))throw new Error('Status response was not a camera list');cameras=d;renderSelector();if(render)renderActive()}
async function post(command,payload={}){const r=await fetch(`/api/cameras/${encodeURIComponent(selectedId)}/${command}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function loadPresets(){const r=await fetch(`/api/cameras/${encodeURIComponent(selectedId)}/presets`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);presetCache.set(selectedId,d.presets||[]);const s=document.getElementById('preset-selector');if(s){s.innerHTML=presetOptions(currentCamera());syncPresetName()}}
async function runAction(b){const id=selectedId,cmd=b.dataset.command,was=b.disabled;b.disabled=true;messages.set(id,{ok:true,text:'Working…'});updateMessage(id);try{if(cmd==='move')await post('move',{pan:Number(b.dataset.pan||0),tilt:Number(b.dataset.tilt||0)});else if(cmd==='stop')await post('stop');else if(cmd==='zoom')await post('zoom',{direction:b.dataset.direction});else if(cmd==='load-presets'||cmd==='refresh-presets')await loadPresets();else if(cmd==='goto-preset'){const t=document.getElementById('preset-selector')?.value;if(!t)throw new Error('Select a preset');const r=await fetch(`/api/cameras/${encodeURIComponent(id)}/presets/${encodeURIComponent(t)}/goto`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`)}else if(cmd==='save-preset'){const t=document.getElementById('preset-selector')?.value,n=document.getElementById('preset-name')?.value||'';if(!t)throw new Error('Select the preset slot to overwrite');const r=await fetch(`/api/cameras/${encodeURIComponent(id)}/presets/${encodeURIComponent(t)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);await loadPresets()}messages.set(id,{ok:true,text:`${cmd} accepted at ${new Date().toLocaleTimeString()}`})}catch(e){messages.set(id,{ok:false,text:e.message})}finally{b.disabled=was;updateMessage(id);await loadCameras(false).catch(()=>{})}}
active.addEventListener('click',e=>{const tab=e.target.closest('.tab[data-tab]');if(tab){activeTab=tab.dataset.tab;active.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(`${activeTab}-panel`)?.classList.add('active');return}if(e.target.id==='clear-console'){const box=document.getElementById('console');if(box){box.textContent='';renderedLogs=''}return}if(e.target.id==='run-diagnostics'){runDiagnostics();return}const b=e.target.closest('button[data-command]');if(b&&!b.disabled)runAction(b)});
active.addEventListener('change',async e=>{if(e.target.id==='preset-selector'){syncPresetName();return}if(e.target.id!=='feed-toggle')return;try{await post('feed',{enabled:e.target.checked});messages.set(selectedId,{ok:true,text:`Live feed ${e.target.checked?'enabled':'disabled'}`})}catch(x){messages.set(selectedId,{ok:false,text:x.message})}await loadCameras()});
selector.addEventListener('change',()=>{selectedId=selector.value;localStorage.setItem('multicam-active-camera',selectedId);renderActive()});
loadCameras().catch(e=>{selector.innerHTML='<option>Camera list unavailable</option>';selector.disabled=true;active.className='error';active.textContent=e.message});setInterval(()=>loadCameras(false).catch(()=>{}),10000);
